# Generated by Django 4.2.3 on 2024-07-07 23:44

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=100)),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=1000
                    ),
                ),
                (
                    "total_deposit",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=1000
                    ),
                ),
                (
                    "referral_code",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=50,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("referred", models.CharField(blank=True, max_length=20)),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ref_bonus",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=1000
                    ),
                ),
                ("btc_address", models.CharField(blank=True, max_length=100)),
                ("eth_address", models.CharField(blank=True, max_length=100)),
                ("usdt_address", models.CharField(blank=True, max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "DigitalTradez User",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, max_length=25)),
                ("wallet_address", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="ijklmno12345",
                        length=10,
                        max_length=20,
                        prefix="WDR",
                        unique=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Withdrawal Requests",
            },
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("email_confirmation", "Email Confirmation"),
                            ("password_reset", "Password Reset"),
                            ("refresh_token", "Refresh token"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Token",
                "verbose_name_plural": "User Tokens",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=100
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("hourly", "hourly"),
                        ],
                        default="daily",
                        max_length=16,
                    ),
                ),
                (
                    "percentage_return",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=100
                    ),
                ),
                (
                    "least_amount",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=1000
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=100
                    ),
                ),
                (
                    "transaction_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=20,
                        max_length=30,
                        prefix="TRX",
                        unique=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("plan_interval_processed", models.BooleanField(default=False)),
                ("interval_count", models.IntegerField(default=0)),
                ("days_count", models.IntegerField(default=1)),
                (
                    "expiry_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            7,
                            14,
                            23,
                            44,
                            54,
                            316845,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users that invested",
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=25)),
                ("wallet_address", models.CharField(blank=True, max_length=100)),
                ("trx_hash", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Users Deposit",
            },
        ),
    ]
