# Generated by Django 4.2.3 on 2024-01-01 17:16

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "userauths",
            "0002_deposit_trx_hash_user_btc_address_user_eth_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plan_interval_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=20,
                prefix="vangard",
                unique=True,
            ),
        ),
    ]
