# Generated by Django 4.2.3 on 2023-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BtcAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(default="btc address", max_length=100)),
                ("initial", models.CharField(default="BTC", max_length=10)),
            ],
            options={
                "verbose_name_plural": "BTC Address",
            },
        ),
        migrations.CreateModel(
            name="EthAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(default="eth address", max_length=100)),
                ("initial", models.CharField(default="ETH", max_length=10)),
            ],
            options={
                "verbose_name_plural": "ETH Address",
            },
        ),
        migrations.CreateModel(
            name="OtherAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(default="eth address", max_length=100)),
                ("initial", models.CharField(default="Other", max_length=10)),
            ],
            options={
                "verbose_name_plural": "USDT Address",
            },
        ),
        migrations.AlterModelOptions(
            name="usercomplaints",
            options={"verbose_name_plural": "Users Complaints"},
        ),
        migrations.AddField(
            model_name="plan",
            name="user_count",
            field=models.IntegerField(default="100"),
        ),
    ]
