COUNTRIES = (
    ('Andorra', ('Andorra')),
    ('UAE', ('United Arab Emirates')),
    ('Afghanistan', ('Afghanistan')),
    ('Antigua & Barbuda', ('Antigua & Barbuda')),
    ('Anguilla', ('Anguilla')),
    ('Albania', ('Albania')),
    ('Armenia', ('Armenia')),
    ('Netherlands Antilles', ('Netherlands Antilles')),
    ('Angola', ('Angola')),
    ('Antarctica', ('Antarctica')),
    ('Argentina', ('Argentina')),
    ('American Samoa', ('American Samoa')),
    ('Ausria', ('Austria')),
    ('Australia', ('Australia')),
    ('Aruba', ('Aruba')),
    ('Azerbaijan', ('Azerbaijan')),
    ('Bosnia and Herzegovina', ('Bosnia and Herzegovina')),
    ('Barbados', ('Barbados')),
    ('Bangladesh', ('Bangladesh')),
    ('Belgium', ('Belgium')),
    ('Burkina Faso', ('Burkina Faso')),
    ('Bulgaria', ('Bulgaria')),
    ('Bahrain', ('Bahrain')),
    ('Burundi', ('Burundi')),
    ('Benin', ('Benin')),
    ('Bermuda', ('Bermuda')),
    ('BN', ('Brunei Darussalam')),
    ('Bolivia', ('Bolivia')),
    ('Brazil', ('Brazil')),
    ('Bahama', ('Bahama')),
    ('Bhutan', ('Bhutan')),
    ('Bouvet Island', ('Bouvet Island')),
    ('Botswana', ('Botswana')),
    ('Belarus', ('Belarus')),
    ('Belize', ('Belize')),
    ('Canada', ('Canada')),
    ('Cocos Islands', ('Cocos (Keeling) Islands')),
    ('Central African Republic', ('Central African Republic')),
    ('Congo', ('Congo')),
    ('Switzerland', ('Switzerland')),
    ('Ivory Coast', ('Ivory Coast')),
    ('Cook Islands', ('Cook Islands')),
    ('Chile', ('Chile')),
    ('Cameroon', ('Cameroon')),
    ('China', ('China')),
    ('Colombia', ('Colombia')),
    ('Costa Rica', ('Costa Rica')),
    ('Cuba', ('Cuba')),
    ('Cape Verde', ('Cape Verde')),
    ('Christmas Island', ('Christmas Island')),
    ('Cyprus', ('Cyprus')),
    ('Czech Republic', ('Czech Republic')),
    ('Germany', ('Germany')),
    ('Djibouti', ('Djibouti')),
    ('Denmark', ('Denmark')),
    ('Dominica', ('Dominica')),
    ('Dominican Republic', ('Dominican Republic')),
    ('Algeria', ('Algeria')),
    ('Ecuador', ('Ecuador')),
    ('Estonia', ('Estonia')),
    ('Egypt', ('Egypt')),
    ('Western Sahara', ('Western Sahara')),
    ('Eritrea', ('Eritrea')),
    ('Spain', ('Spain')),
    ('Ethiopia', ('Ethiopia')),
    ('Finland', ('Finland')),
    ('Fiji', ('Fiji')),
    ('FK', ('Falkland Islands (Malvinas)')),
    ('Micronesia', ('Micronesia')),
    ('FO', ('Faroe Islands')),
    ('France', ('France')),
    ('France, Metropolitan', ('France, Metropolitan')),
    ('Gabon', ('Gabon')),
    ('UK', ('United Kingdom (Great Britain)')),
    ('Grenada', ('Grenada')),
    ('Georgia', ('Georgia')),
    ('GF', ('French Guiana')),
    ('Ghana', ('Ghana')),
    ('GI', ('Gibraltar')),
    ('Greenland', ('Greenland')),
    ('Gambia', ('Gambia')),
    ('Guinea', ('Guinea')),
    ('Guadeloupe', ('Guadeloupe')),
    ('Equatorial Guinea', ('Equatorial Guinea')),
    ('Greece', ('Greece')),
    ('South Georgia and the South Sandwich Islands', ('South Georgia and the South Sandwich Islands')),
    ('Guatemala', ('Guatemala')),
    ('Guam', ('Guam')),
    ('Guinea-Bissau', ('Guinea-Bissau')),
    ('Guyana', ('Guyana')),
    ('Hong Kong', ('Hong Kong')),
    ('Heard & McDonald Islands', ('Heard & McDonald Islands')),
    ('Honduras', ('Honduras')),
    ('Croatia', ('Croatia')),
    ('Haiti', ('Haiti')),
    ('Hungary', ('Hungary')),
    ('Indonesia', ('Indonesia')),
    ('Ireland', ('Ireland')),
    ('Israel', ('Israel')),
    ('India', ('India')),
    ('British Indian Ocean Territory', ('British Indian Ocean Territory')),
    ('Iraq', ('Iraq')),
    ('Islamic Republic of Iran', ('Islamic Republic of Iran')),
    ('Iceland', ('Iceland')),
    ('Italy', ('Italy')),
    ('Jamaica', ('Jamaica')),
    ('Jordan', ('Jordan')),
    ('Japan', ('Japan')),
    ('Kenya', ('Kenya')),
    ('Kyrgyzstan', ('Kyrgyzstan')),
    ('Cambodia', ('Cambodia')),
    ('Kiribati', ('Kiribati')),
    ('Comoros', ('Comoros')),
    ('St. Kitts and Nevis', ('St. Kitts and Nevis')),
    ('Korea, Democratic People\'s Republic of', ('Korea, Democratic People\'s Republic of')),
    ('Korea, Republic of', ('Korea, Republic of')),
    ('Kuwait', ('Kuwait')),
    ('Cayman Islands', ('Cayman Islands')),
    ('Kazakhstan', ('Kazakhstan')),
    ('Lao People\'s Democratic Republic', ('Lao People\'s Democratic Republic')),
    ('Lebanon', ('Lebanon')),
    ('Saint Lucia', ('Saint Lucia')),
    ('Liechtenstein', ('Liechtenstein')),
    ('Sri Lanka', ('Sri Lanka')),
    ('Liberia', ('Liberia')),
    ('Lesotho', ('Lesotho')),
    ('Lithuania', ('Lithuania')),
    ('Luxembourg', ('Luxembourg')),
    ('Latvia', ('Latvia')),
    ('Libyan Arab Jamahiriya', ('Libyan Arab Jamahiriya')),
    ('Morocco', ('Morocco')),
    ('Monaco', ('Monaco')),
    ('Moldova, Republic of', ('Moldova, Republic of')),
    ('Madagascar', ('Madagascar')),
    ('Marshall Islands', ('Marshall Islands')),
    ('Mali', ('Mali')),
    ('Mongolia', ('Mongolia')),
    ('Myanmar', ('Myanmar')),
    ('Macau', ('Macau')),
    ('Northern Mariana Islands', ('Northern Mariana Islands')),
    ('Martinique', ('Martinique')),
    ('Mauritania', ('Mauritania')),
    ('Monserrat', ('Monserrat')),
    ('Malta', ('Malta')),
    ('Mauritius', ('Mauritius')),
    ('Maldives', ('Maldives')),
    ('Malawi', ('Malawi')),
    ('Mexico', ('Mexico')),
    ('Malaysia', ('Malaysia')),
    ('Mozambique', ('Mozambique')),
    ('Namibia', ('Namibia')),
    ('New Caledonia', ('New Caledonia')),
    ('Niger', ('Niger')),
    ('Norfolk Island', ('Norfolk Island')),
    ('Nigeria', ('Nigeria')),
    ('Nicaragua', ('Nicaragua')),
    ('Netherlands', ('Netherlands')),
    ('Norway', ('Norway')),
    ('Nepal', ('Nepal')),
    ('Nauru', ('Nauru')),
    ('Niue', ('Niue')),
    ('New Zealand', ('New Zealand')),
    ('Oman', ('Oman')),
    ('Panama', ('Panama')),
    ('Peru', ('Peru')),
    ('French Polynesia', ('French Polynesia')),
    ('Papua New Guinea', ('Papua New Guinea')),
    ('Phillipines', ('Philippines')),
    ('Pakistan', ('Pakistan')),
    ('Poland', ('Poland')),
    ('PM', ('St. Pierre & Miquelon')),
    ('Pitcairn', ('Pitcairn')),
    ('Puerto Rico', ('Puerto Rico')),
    ('Portugal', ('Portugal')),
    ('Palau', ('Palau')),
    ('Paraguay', ('Paraguay')),
    ('Qatar', ('Qatar')),
    ('Reunion', ('Reunion')),
    ('Romania', ('Romania')),
    ('RUssia', ('Russian Federation')),
    ('Rwanda', ('Rwanda')),
    ('Saudi Arabia', ('Saudi Arabia')),
    ('Solomon Islands', ('Solomon Islands')),
    ('Seychelles', ('Seychelles')),
    ('Sudan', ('Sudan')),
    ('Sweden', ('Sweden')),
    ('Singapore', ('Singapore')),
    ('St. Helena', ('St. Helena')),
    ('Slovenia', ('Slovenia')),
    ('Svalbard', ('Svalbard & Jan Mayen Islands')),
    ('Slovokia', ('Slovakia')),
    ('Sirra Leone', ('Sierra Leone')),
    ('San Marino', ('San Marino')),
    ('Senegal', ('Senegal')),
    ('Somalia', ('Somalia')),
    ('Suriname', ('Suriname')),
    ('Sao Tome', ('Sao Tome & Principe')),
    ('El Salvador', ('El Salvador')),
    ('Syrian Arab Republic', ('Syrian Arab Republic')),
    ('Swaziland', ('Swaziland')),
    ('Turks & Caicos Islands', ('Turks & Caicos Islands')),
    ('Chad', ('Chad')),
    ('French Southern Territories', ('French Southern Territories')),
    ('Togo', ('Togo')),
    ('Thailand', ('Thailand')),
    ('Tajikistan', ('Tajikistan')),
    ('Tokelau', ('Tokelau')),
    ('Turkmenistan', ('Turkmenistan')),
    ('Tunisia', ('Tunisia')),
    ('Tonga', ('Tonga')),
    ('East Timor', ('East Timor')),
    ('Turkey', ('Turkey')),
    ('Trinidad', ('Trinidad & Tobago')),
    ('Tuvalu', ('Tuvalu')),
    ('Taiwan, Province of China', ('Taiwan, Province of China')),
    ('Tanzania, United Republic of', ('Tanzania, United Republic of')),
    ('Ukraine', ('Ukraine')),
    ('Uganda', ('Uganda')),
    ('United States Minor', ('United States Minor Outlying Islands')),
    ('United States', ('United States of America')),
    ('Uruguay', ('Uruguay')),
    ('Uzbekistan', ('Uzbekistan')),
    ('Vatican City', ('Vatican City State (Holy See)')),
    ('VC', ('St. Vincent & the Grenadines')),
    ('Venezuela', ('Venezuela')),
    ('VG', ('British Virgin Islands')),
    ('VI', ('United States Virgin Islands')),
    ('Viet Nam', ('Viet Nam')),
    ('Vunauatu', ('Vanuatu')),
    ('WF', ('Wallis & Futuna Islands')),
    ('Samoa', ('Samoa')),
    ('Yemen', ('Yemen')),
    ('Mayotte', ('Mayotte')),
    ('Yugoslavia', ('Yugoslavia')),
    ('South Africa', ('South Africa')),
    ('Zambia', ('Zambia')),
    ('Zaire', ('Zaire')),
    ('Zimbabwe', ('Zimbabwe')),
    ('ZZ', ('Unknown or unspecified country')),
)
sorted_countries = sorted(COUNTRIES, key=lambda x: x[1])